# Docker Compose Configuration
version: '3.8'

services:
  claude-chat:
    build: .
    container_name: claude-chat
    restart: unless-stopped
    
    # Port mapping: host:container
    # Container runs on 5000, exposed on host as 5002
    ports:
      - "5002:5000"
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Volume mounts
    volumes:
      # Persist logs outside container
      - ./logs:/app/logs
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: claude-chat-network